### ISSUE TITLE
Remove `dask` as a dependency for v2.7.0

### ISSUE THREAD

**Issue by tomvothecoder** [conda-forge/e3sm_diags-feedstock#17]
### Comment:

Related to https://github.com/E3SM-Project/e3sm_diags/issues/582

**Comment by xylar** [comment]
@tomvothecoder, each time there is a version bump, I just go back to the main GitHub repo and compare file changes between the newest and the previous version to make sure I catch dependency changes.  So I think as long as the conda recipe there is kept current, there's no need to document dependency changes here as well. Still, it does no harm...

**Comment by tomvothecoder** [comment]
@xylar Gotcha, good to see how you manage the recipes. This process hasn't been ingrained into me yet, so I open an issue in the feedstock as a reminder to update the dependencies haha.

I'll close this since it isn't needed.
